// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.10 backRooms.glb 
// */

// import React, { useRef } from 'react'
// import { useGLTF, useAnimations } from '@react-three/drei'

// export function Model(props) {
//   const group = useRef()
//   const { nodes, materials, animations } = useGLTF('/backRooms.glb')
//   const { actions } = useAnimations(animations, group)
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group name="Scene">
//         <group name="SkirtingBoards_5" position={[-6.011, 0.219, 40.157]} rotation={[Math.PI, -1.563, Math.PI]} scale={[2.319, 1.849, 2.073]}>
//           <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.SkirtNew} position={[0, -0.09, 0]} />
//         </group>
//         <group name="Column004_6" position={[-5.669, 1.976, 42.462]} rotation={[Math.PI, -1.563, Math.PI]} scale={[2.319, 1.849, 2.073]}>
//           <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Columns} position={[0, -0.04, 0]} />
//         </group>
//         <group name="Walls_23" position={[-5.165, 1.145, 42.135]} rotation={[-Math.PI, 0.008, -Math.PI]} scale={[2.073, 1.849, 2.319]}>
//           <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.Wall} position={[0, -0.03, 0]} />
//         </group>
//         <group name="Sketchfab_model002" position={[0.428, -0.01, 55.038]} rotation={[-Math.PI / 2, 0, -0.006]} scale={[0.005, 0.004, 0.005]}>
//           <group name="Collada_visual_scene_group" position={[0, 0.003, 0]} rotation={[Math.PI / 2, 0, 0]}>
//             <group name="cl_body_01" position={[-1000, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
//               <mesh name="defaultMaterial002" geometry={nodes.defaultMaterial002.geometry} material={materials.cl_body_mat} rotation={[0, 0, -0.149]} />
//             </group>
//             <group name="cl_body_02" position={[100, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
//               <mesh name="defaultMaterial001" geometry={nodes.defaultMaterial001.geometry} material={materials.cl_body_mat} rotation={[0, 0, -0.138]} />
//             </group>
//             <group name="cl_body_03" position={[-460, 66.507, -0.001]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
//               <mesh name="defaultMaterial003" geometry={nodes.defaultMaterial003.geometry} material={materials.cl_body_mat} />
//             </group>
//             <group name="cl_body_04" position={[600, 0, -0.001]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
//               <mesh name="defaultMaterial" geometry={nodes.defaultMaterial.geometry} material={materials.cl_body_mat} />
//             </group>
//           </group>
//         </group>
//         <group name="Sketchfab_model005" position={[-15.203, 0, 56.378]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.342, 0.164, 0.153]}>
//           <group name="Collada_visual_scene_group001" rotation={[Math.PI / 2, 0, 0]} />
//         </group>
//         <group name="Sketchfab_model" position={[8.102, -0.057, 25.56]} rotation={[-Math.PI / 2, 0, -1.573]} scale={[0.051, 0.038, 0.03]}>
//           <group name="88b38f8db19d44e98a0a6580aa47f0f9fbx" rotation={[Math.PI / 2, 0, 0]}>
//             <group name="Object_2">
//               <group name="RootNode">
//                 <group name="door" position={[-20.073, 62.415, 29.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.073}>
//                   <group name="Object_7" position={[53.162, 405.59, 82.842]}>
//                     <mesh name="door_Door_0" geometry={nodes.door_Door_0.geometry} material={materials.Door} position={[0.001, 0, 0]} />
//                     <mesh name="door_Hand_0" geometry={nodes.door_Hand_0.geometry} material={materials.Hand} position={[0.001, 0, 0]} />
//                     <mesh name="door_Lock_0" geometry={nodes.door_Lock_0.geometry} material={materials.Lock} position={[0.001, 0, 0]} />
//                     <mesh name="door_Lock_2_0" geometry={nodes.door_Lock_2_0.geometry} material={materials.Lock_2} position={[0.001, 0, 0]} />
//                   </group>
//                 </group>
//                 <group name="rama" position={[-16.172, 68.493, -0.695]} rotation={[-Math.PI / 2, 0, 0]} scale={0.073}>
//                   <mesh name="rama_Door_0" geometry={nodes.rama_Door_0.geometry} material={materials.Door} position={[0.001, 0, 0]} />
//                 </group>
//               </group>
//             </group>
//           </group>
//         </group>
//         <group name="Sketchfab_model001" position={[9.381, 0, 58.49]} rotation={[-Math.PI / 2, 0, -2.558]} scale={[0.145, 0.128, 0.155]}>
//           <group name="9d0581fd752b47babd3a9ad92b3b3df4fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
//             <group name="RootNode001" position={[0, 0, -0.005]}>
//               <group name="belt1_lp" position={[0, 0, -0.005]} rotation={[-1.309, 0, -Math.PI]} scale={[107.331, 78.68, 116.335]}>
//                 <mesh name="belt1_lp_belt_0" geometry={nodes.belt1_lp_belt_0.geometry} material={materials['belt.002']} />
//               </group>
//               <group name="belt2_lp" position={[0, 0, -0.005]} rotation={[-1.163, -0.038, 3.053]} scale={[107.331, 78.68, 85.585]}>
//                 <mesh name="belt2_lp_belt_0" geometry={nodes.belt2_lp_belt_0.geometry} material={materials['belt.002']} />
//               </group>
//               <group name="belt3_lp" position={[0, 0, -0.005]} rotation={[0.185, -1.292, -1.536]} scale={[127.248, 79.801, 99.473]}>
//                 <mesh name="belt3_lp_belt_0" geometry={nodes.belt3_lp_belt_0.geometry} material={materials['belt.002']} />
//               </group>
//               <group name="belt_lp" position={[0, 0, -0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={[96.445, 100.466, 100]}>
//                 <mesh name="belt_lp_belt_0" geometry={nodes.belt_lp_belt_0.geometry} material={materials['belt.002']} />
//               </group>
//               <group name="card_lp" position={[0, 0, -0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
//                 <mesh name="card_lp_card_0" geometry={nodes.card_lp_card_0.geometry} material={materials['card.002']} />
//               </group>
//               <group name="dress1_lp" position={[0, 0, -0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
//                 <mesh name="dress1_lp_dress1_0" geometry={nodes.dress1_lp_dress1_0.geometry} material={materials['dress1.002']} />
//               </group>
//               <group name="dress_lp" position={[0, 0, -0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
//                 <mesh name="dress_lp_dress_0" geometry={nodes.dress_lp_dress_0.geometry} material={materials['dress.002']} />
//               </group>
//               <group name="hat_lp" position={[0, 0, -0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
//                 <group name="hat_lp_hat_0" rotation={[0, 0, -0.109]}>
//                   <mesh name="hat_lp_hat_0002" geometry={nodes.hat_lp_hat_0002.geometry} material={materials['material.002']} />
//                   <mesh name="hat_lp_hat_0002_1" geometry={nodes.hat_lp_hat_0002_1.geometry} material={materials['body.002']} />
//                 </group>
//               </group>
//               <group name="heels_lp" position={[0, 0, -0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={113.724}>
//                 <mesh name="heels_lp_heels_0" geometry={nodes.heels_lp_heels_0.geometry} material={materials['heels.002']} />
//               </group>
//             </group>
//           </group>
//         </group>
//         <group name="Sketchfab_model003" position={[9.381, 0, 58.49]} rotation={[-Math.PI / 2, 0, -2.558]} scale={[1.398, 1.232, 1.5]}>
//           <group name="420e4c6a72bb49dea2c0b4ad7488ebc3fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
//             <group name="Object_2001">
//               <group name="RootNode002">
//                 <group name="Armature" position={[0, 414.862, -54.809]} rotation={[-1.253, 0, 0]} scale={100} />
//                 <group name="Head" scale={55.075} />
//               </group>
//             </group>
//           </group>
//         </group>
//         <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.top} position={[-5.682, 3.743, 45.325]} scale={[20.123, 2.012, 20.123]} />
//         <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.top} position={[-7.963, 0, 43.016]} scale={[22.5, 1, 22.5]} />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/backRooms.glb')
