/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 nurse-head.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/nurse-head.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.078, 1.465, 1.207]} rotation={[-0.369, 0, 0]}>
        <mesh geometry={nodes.hat_lp_hat_0005.geometry} material={materials['material.007']} />
        <mesh geometry={nodes.hat_lp_hat_0005_1.geometry} material={materials['body.008']} />
        <mesh geometry={nodes.hat_lp_hat_0005_2.geometry} material={materials['material.006']} />
        <mesh geometry={nodes.hat_lp_hat_0005_3.geometry} material={materials['body.007']} />
      </group>
    </group>
  )
}

useGLTF.preload('/nurse-head.glb')
