/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 backRooms.glb 
*/

import { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial } from "three";

const state = {
  visible: false
}

export function Model() {
  const { scene, nodes, materials }: any = useGLTF("/backRooms.glb");

  useEffect(() => {
    for (const [keys, values] of Object.entries<MeshStandardMaterial>(
      materials
    )) {
      if (keys !== "ceiling") {
        values.side = 0;
      }
    }

    if (materials.Pillars && materials.walls) {
      materials.Pillars.roughness = 0.5;
      materials.walls.roughness = 0.95;
    }
  }, [materials, nodes, scene]);

  return (
    <group dispose={null}>
    <group position={[0.61, 0.111, 55.092]} rotation={[-Math.PI / 2, 0, -0.006]} scale={[0.005, 0.004, 0.005]}>
      <group position={[0, 0.002, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <group position={[-1000, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial002.geometry} material={materials.cl_body_mat} rotation={[0, 0, -0.149]} />
        </group>
        <group position={[100, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial001.geometry} material={materials.cl_body_mat} rotation={[0, 0, -0.138]} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.defaultMaterial003.geometry} material={materials.cl_body_mat} position={[-460, 66.507, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh castShadow receiveShadow geometry={nodes.defaultMaterial.geometry} material={materials.cl_body_mat} position={[600, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
    <group position={[-5.669, 1.976, 42.462]} rotation={[Math.PI, -1.563, Math.PI]} scale={[2.319, 1.849, 2.073]}>
      <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials.Pillars} position={[0, 0.012, 0]} />
    </group>
  <mesh castShadow receiveShadow geometry={nodes.doorRef.geometry} material={materials.walls} position={[-2.488, 2.099, 50.2]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={[2, 1, 0.961]} />
   { state.visible && <mesh castShadow receiveShadow geometry={nodes.doorRef2.geometry} material={materials['walls.004']} position={[-2.487, 2.099, 50.2]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={[2, 1, 0.961]} />}
    <mesh castShadow receiveShadow  geometry={nodes['F-material022'].geometry} material={materials.walls} position={[-9.01, 2.099, 29.268]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[2, 1, 1]} />
    <mesh castShadow receiveShadow geometry={nodes['F-material023'].geometry} material={materials.walls} position={[5.064, 2.099, 45.587]} rotation={[0, 1.567, 1.571]} scale={[2, 1, 0.512]} />
    <mesh castShadow receiveShadow geometry={nodes['F-material024'].geometry} material={materials.walls} position={[-13.571, 2.099, 56.478]} rotation={[0, 0, Math.PI / 2]} scale={[2, 1, 1]} />
   { state.visible && <mesh castShadow receiveShadow geometry={nodes['door#2'].geometry} material={materials.board} position={[-12.166, 0.137, 50.252]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.171, 0.085, 0.166]} />}
    <mesh castShadow receiveShadow geometry={nodes['F-material001'].geometry} material={materials.walls} position={[-13.591, 2.099, 45.497]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[2, 1, 1]} />
    <mesh castShadow receiveShadow geometry={nodes['M-material004'].geometry} material={materials.board} position={[-1.257, 2.199, 34.232]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.1, 0.083, 0.166]} />
    <mesh castShadow receiveShadow geometry={nodes['F-material002'].geometry} material={materials.walls} position={[-4.875, 2.099, 32.206]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[2, 0.497, 0.726]} />
    <mesh castShadow receiveShadow geometry={nodes['F-material003'].geometry} material={materials.walls} position={[-1.311, 2.099, 32.23]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[2, 0.497, 0.726]} />
    <mesh castShadow receiveShadow geometry={nodes['F-material004'].geometry} material={materials.walls} position={[-1.65, 2.099, 31.731]} rotation={[Math.PI, -0.023, -Math.PI / 2]} scale={[2, 0.497, 0.726]} />
    <mesh castShadow receiveShadow geometry={nodes['F-material005'].geometry} material={materials.walls} position={[-1.751, 2.099, 42.688]} rotation={[Math.PI, -0.023, -Math.PI / 2]} scale={[2, 0.497, 0.726]} />
    <mesh castShadow receiveShadow geometry={nodes['F-material006'].geometry} material={materials.walls} position={[-4.825, 2.099, 28.687]} rotation={[Math.PI, 1.545, -1.571]} scale={[2, 0.497, 0.726]} />
    <mesh castShadow receiveShadow geometry={nodes['F-material007'].geometry} material={materials.walls} position={[-11.317, 2.099, 24.966]} rotation={[0, 0, Math.PI / 2]} scale={[2, 1.173, 0.512]} />
    <mesh castShadow receiveShadow geometry={nodes['F-material008'].geometry} material={materials.walls} position={[-23.304, 2.099, 37.443]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[2, 1.251, 0.512]} />
    <mesh castShadow receiveShadow geometry={nodes['F-material009'].geometry} material={materials.walls} position={[0.289, 2.099, 62.092]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={[2, 1.173, 0.512]} />
    <mesh castShadow receiveShadow geometry={nodes['F-material010'].geometry} material={materials.walls} position={[10.979, 2.099, 49.564]} rotation={[0, 1.567, 1.571]} scale={[2, 1.251, 0.512]} />
    <mesh castShadow receiveShadow geometry={nodes['F-material011'].geometry} material={materials.carpet} position={[0.289, 0.034, 70.454]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[2, 1.173, 0.512]} />
    <group position={[-17.988, 3.893, 31.262]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.337, 2.693, 1]}>
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_1.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_2.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_3.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_4.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_5.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_6.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_7.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_8.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_9.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_10.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_11.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_12.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_13.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_14.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_15.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_16.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_17.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_18.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_19.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_20.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_21.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_22.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_23.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_24.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_25.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_26.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_27.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_28.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_29.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_30.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_31.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_32.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_33.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_34.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_35.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_36.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_37.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_38.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_39.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_40.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_41.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_42.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_43.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_44.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_45.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_46.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_47.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_48.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_49.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_50.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_51.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_52.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_53.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_54.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_55.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_56.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_57.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_58.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_59.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_60.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_61.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_62.geometry} material={materials.ceiling} />
      <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_63.geometry} material={materials.ceiling} />
    </group>
    <mesh receiveShadow geometry={nodes['F-material014'].geometry} material={materials['walls.003']} position={[-13.591, 2.099, 45.497]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[2, 1, 1]} />
  </group>
  );
}

useGLTF.preload("/backRooms.glb");
