/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 newBackroom.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model() {
  const { nodes, materials }:any = useGLTF('/newBackroom.glb')
  return (
    <group dispose={null}>
      <group position={[6.195, 2.072, 3.547]}>
        <mesh geometry={nodes.Object_19.geometry} material={materials.SkirtNew} scale={[1, 1.294, 1]} />
      </group>
      <group position={[5.966, 2.194, 5.552]}>
        <mesh geometry={nodes.Object_21.geometry} material={materials.Wall} scale={[1, 1.294, 1]} />
      </group>
      <mesh geometry={nodes.Cube002.geometry} material={materials.Columns} position={[8.231, 1.763, 22.968]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[1.197, 4.638, 1.37]} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[91.018, 5.961, 88.565]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 3.849, 1]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Floor} position={[-5.083, 0, 43.004]} scale={[20.123, 2.012, 20.123]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Floor.002']} position={[14.889, 0, 2.561]} scale={[20.123, 2.012, 20.123]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.SkirtNew} position={[-6.011, 0.219, 40.157]} rotation={[Math.PI, -1.563, Math.PI]} scale={[2.319, 1.849, 2.073]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Columns} position={[-5.669, 1.976, 42.462]} rotation={[Math.PI, -1.563, Math.PI]} scale={[2.319, 1.849, 2.073]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Wall} position={[-5.165, 1.145, 42.135]} rotation={[-Math.PI, 0.008, -Math.PI]} scale={[2.073, 1.849, 2.319]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Columns} position={[24.65, 2.065, -2.314]} />
    </group>
  )
}

useGLTF.preload('/newBackroom.glb')
