/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 flash-lite_flashlight.glb 
Author: AndrewHunt95 (https://sketchfab.com/AndrewHunt95)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flash-lite-flashlight-e20e52c7a0eb466086af727588839d48
Title: Flash-Lite Flashlight
*/


import { useGLTF } from '@react-three/drei'
import { useRef } from 'react'



export const Flashlight =() => {

const flashRef = useRef<any>()

  const { nodes, materials }:any = useGLTF('/flash-lite_flashlight.glb')
  return (
    
      <group dispose={null}  ref={flashRef} castShadow>
      <group rotation={[Math.PI / 2, 0, 0]} >
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.015}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={100} >
            <mesh geometry={nodes.Cube012_FlashlightBody_0.geometry} material={materials.FlashlightBody} />
            <mesh geometry={nodes.Cube012_FlashlightGlass_0.geometry} material={materials.FlashlightGlass} />
          </group>
        </group>
      </group>
    </group>
    
    
  )
}

useGLTF.preload('/flash-lite_flashlight.glb')
