/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 houseRef.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model() {
  const { nodes, materials }:any = useGLTF('/houseRef.glb')
  return (
    <group dispose={null}>
      <mesh geometry={nodes.Room.geometry} material={materials.Plaster_wall} position={[-5.3, 0, 13.441]} scale={[1.788, 1, 1.798]} />
      <mesh geometry={nodes.Room001.geometry} material={materials.Plaster_wall} position={[-5.378, 0, 20.16]} scale={[1.43, 1, 2.32]} />
      <mesh geometry={nodes.Room007.geometry} material={materials.Material} position={[0.535, 0, 27.849]} scale={[0.801, 1, 1]} />
      <mesh geometry={nodes.Room002.geometry} material={materials.Plaster_wall} position={[3.005, 0, 27.889]} />
      <mesh geometry={nodes.Room003.geometry} material={materials.Plaster_wall} position={[2.888, 0, 18.837]} />
      <mesh geometry={nodes.Room004.geometry} material={materials.Plaster_wall} position={[12.841, 0, 13.487]} />
      <mesh geometry={nodes.Room006.geometry} material={materials.Plaster_wall} position={[7.969, 0, 13.43]} />
      <mesh geometry={nodes.Room008.geometry} material={materials.Plaster_wall} position={[12.092, 0, 22.719]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Material} position={[5.408, 0, 15.94]} rotation={[0, -Math.PI / 2, 0]} scale={[2.5, 1, 11]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Material} position={[5.382, 0, 20.938]} rotation={[0, -Math.PI / 2, 0]} scale={[2.5, 1, 11]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.Material} position={[5.316, 0, 25.934]} rotation={[0, -Math.PI / 2, 0]} scale={[2.5, 1, 11]} />
      <mesh geometry={nodes.Handle.geometry} material={materials.Handle_material} position={[-0.545, 0.122, 0.018]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Handle001.geometry} material={materials.Handle_material} position={[-0.545, 0.122, 0.018]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Roller_bottom.geometry} material={materials.Plastic_roller_material} position={[0, -1.7, 0]} />
      <mesh geometry={nodes.StringL.geometry} material={materials.String_material} position={[0.352, 0, 0]} />
      <mesh geometry={nodes.StringfL.geometry} material={materials.String_material} position={[0.352, 0, 0.021]} />
      <mesh geometry={nodes.StringfC.geometry} material={materials.String_material} position={[0, 0, 0.021]} />
      <mesh geometry={nodes.StringbL.geometry} material={materials.String_material} position={[0.352, 0, -0.021]} />
      <mesh geometry={nodes.Venetian_updown.geometry} material={materials.String_material} position={[0.47, -0.03, 0.023]} />
      <mesh geometry={nodes.Baseboard.geometry} material={materials.Baseboard_material} />
      <mesh geometry={nodes.Room009.geometry} material={materials.Material} position={[2.973, 0, 27.802]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Baseboard001.geometry} material={materials.Baseboard_material} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/houseRef.glb')
