/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 maze.glb 
Author: victor.darras (https://sketchfab.com/victor.darras)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/maze-b1b79eaa6aaf47ad84b7645f1b9c36dd
Title: Maze
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Maze =(props:any)=> {
  const { nodes, materials }:any = useGLTF('/maze.glb')
  return (
    <group {...props} dispose={null} castShadow receiveShadow>
      <mesh geometry={nodes.Object_2.geometry} material={materials.palette} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/maze.glb')

export default Maze
