/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 maze-new.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model() {
  const { nodes, materials }:any = useGLTF('/maze-new.glb')

  if(materials){
    materials["palette.005"].sides = 0
    materials["palette.005"].roughness = 0
  }

  return (
    <group dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['palette.005']} position={[0, 1.659, 0]} />
      </group>
      <group position={[-1.249, 5.047, 18.186]} rotation={[-Math.PI / 2, 0, 1.601]}>
        <mesh geometry={nodes.Object_2001.geometry} material={materials.material} position={[18.496, -45.639, -2.636]} rotation={[0, 0, 3.128]} scale={[1.182, 1.367, 1.652]} />
      </group>
      <mesh geometry={nodes.Rope_Rope_0.geometry} material={materials.Rope} position={[2.484, -55.369, 136.376]} />
    </group>
  )
}

useGLTF.preload('/maze-new.glb')
