/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 nurse-head.glb 
*/

import  { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber';

export function NurseHead() {
  const { nodes, materials }:any = useGLTF('/nurse-head.glb')

  const nurseHead = useRef<any>();


  const { camera } = useThree();
  
  useFrame(()=>{//Get the nurse head to look a the camera with each frame
    nurseHead.current.lookAt(camera.position.x, camera.position.y, camera.position.z)
  })

  return (
    <group position={[14.37, 2.65, 58.93]} dispose={null}>
     <group  scale={0.14}>
       <mesh castShadow ref={nurseHead}> 
        <mesh geometry={nodes.hat_lp_hat_0005_2.geometry} material={materials['material.006']} />
        <mesh geometry={nodes.hat_lp_hat_0005_3.geometry} material={materials['body.007']} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/nurse-head.glb')
