/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 nurse-head.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber';

export function NurseHead() {
  const { nodes, materials }:any = useGLTF('/nurse-head.glb')

  const test = useRef<any>();


  const { camera } = useThree();
  
  useFrame(()=>{
    test.current.lookAt(camera.position)
  })

  return (
    <group position={[14.381, 2.35, 59.0]} dispose={null}>
      <group  rotation={[-2.18, 0, 0]} scale={0.13}>
        <mesh geometry={nodes.hat_lp_hat_0004.geometry} material={materials['material.004']} />
        <mesh ref={test} geometry={nodes.hat_lp_hat_0004_1.geometry} material={materials['body.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/nurse-head.glb')
