/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 nurse.glb 
*/

import {  useGLTF } from '@react-three/drei'


export function Nurse() {
  const { nodes, materials }:any = useGLTF('/nurse.glb')
 
  return (
    <group position={[14.35, 0.35, 58.92]} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -2.558]} scale={[0.145, 0.128, 0.155]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 0, -0.005]}>
            <mesh castShadow geometry={nodes.belt1_lp_belt_0.geometry} material={materials['belt.002']} position={[0, 0, -0.005]} rotation={[-1.309, 0, -Math.PI]} scale={[107.331, 78.68, 116.335]} />
            <mesh castShadow geometry={nodes.belt2_lp_belt_0.geometry} material={materials['belt.002']} position={[0, 0, -0.005]} rotation={[-1.163, -0.038, 3.053]} scale={[107.331, 78.68, 85.585]} />
            <mesh castShadow  geometry={nodes.belt3_lp_belt_0.geometry} material={materials['belt.002']} position={[0, 0, -0.005]} rotation={[0.185, -1.292, -1.536]} scale={[127.248, 79.801, 99.473]} />
            <mesh castShadow geometry={nodes.belt_lp_belt_0.geometry} material={materials['belt.002']} position={[0, 0, -0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={[96.445, 100.466, 100]} />
            <mesh castShadow geometry={nodes.card_lp_card_0.geometry} material={materials['card.002']} position={[0, 0, -0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            <mesh castShadow geometry={nodes.dress1_lp_dress1_0.geometry} material={materials['dress1.002']} position={[0, 0, -0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            <mesh castShadow geometry={nodes.dress_lp_dress_0.geometry} material={materials['dress.002']} position={[0, 0, -0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            <mesh castShadow geometry={nodes.heels_lp_heels_0.geometry} material={materials['heels.002']} position={[0, 0, -0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={113.724} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/nurse.glb')
