/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 nurse-head.glb 
*/

import  { useEffect, useRef } from 'react'
import { PositionalAudio, useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber';
import * as THREE from "three";
import { buffer } from 'three/examples/jsm/nodes/Nodes.js';

export function NurseHead() {
  const { nodes, materials }:any = useGLTF('/nurse-head.glb')

  const nurseHead = useRef<any>();
  const ref = useRef<any>();
  const sounds = "./sounds/whispers.mp3"
  const listener = new THREE.AudioListener();
  const { camera } = useThree();
  
  useFrame(()=>{//Get the nurse head to look a the camera with each frame
    nurseHead.current.lookAt(camera.position.x, camera.position.y, camera.position.z)
  })

 useEffect(()=>{
  console.log(ref.current)
  ref.current.setRolloffFactor(7.5)
  ref.current.setBuffer(buffer)
 },[])

  return (
    <group position={[15.35, 2.75, 25.67]} dispose={null}>
     <group  scale={0.14}>
       <mesh  ref={nurseHead}> 
        <mesh  castShadow geometry={nodes.hat_lp_hat_0005_2.geometry} material={materials['material.006']} />
        <mesh castShadow geometry={nodes.hat_lp_hat_0005_3.geometry} material={materials['body.007']} />
        <PositionalAudio ref={ref} autoplay load={THREE.AudioLoader} url={sounds} listener={listener}/>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/nurse-head.glb')
